apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "service.match.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "service.labels.standard" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ if .Values.image.tag }}{{.Values.image.tag }}{{ else }}{{ .Chart.Version }}{{ end }}"
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          {{- range $key, $val := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
