replicaCount: 1
image:
  repository: registry.choerodon.dev.hithinksoft.com/hithinksoft-wrec/wrec-web
  tag: ^[0~9]{4}.[0~9]{2}.[0~9]{2}-[0~9]{6}-master$

service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  host: wrec-web-pre.staging.hithinksoft.com
  path: /
  annotations: {}

extraEnv:
  NGINX_WREC_API_HOST: http://wrec-api-test.staging.hithinksoft.com
